#!/usr/bin/perl
use Socket;
socket(SERVEUR, PF_INET, SOCK_STREAM, getprotobyname('tcp'));
setsockopt(SERVEUR, SOL_SOCKET, SOREUSEADDR, 1);

$mon_adresse = sockaddr_in("7777", INADDR_ANY);

bind(SERVEUR,$mon_adresse) || die("bind");

listen(SERVEUR, SOMAXCONN) || die("listen");
autoflush CLIENT 1;
while(accept(CLIENT, SERVEUR)){
    $pid = fork;
    if($pid == 0)
    {
	while(<CLIENT>){
	    print CLIENT $_;
	}
	exit 0;
    }
}
close (SERVEUR);
