#!/usr/bin/perl

use Socket;

sub lireFichier
{
    
}

sub simple_serveur
{
    %set = lireFichier();
    socket(SERVEUR, PF_INET, SOCK_STREAM, getprotobyname('tcp'));
    setsockopt(SERVEUR, SOL_SOCKET, SOREUSEADDR, 1);

    $mon_adresse = sockaddr_in($set{"port"}, INADDR_ANY);

    bind(SERVEUR,$mon_adresse) || die("bind");

    listen(SERVEUR, $set{"clients"}) || die("listen");
    autoflush CLIENT 1;
    while(accept(CLIENT, SERVEUR))
    {
	$pid = fork;
	if($pid == 0)
	{
	    while(<CLIENT>)
	    {
		print CLIENT $_;
	    }
	    exit 0;
	}
    }
    close (SERVEUR);
}

sub get_request
{
    %set = lireFichier();
    socket(SERVEUR, PF_INET, SOCK_STREAM, getprotobyname('tcp'));
    $adresse = inet_aton(@ARGV[0]) || die("inet_aton");
    $adresse_complete = sockaddr_in($set{"port"}, $adresse) || die ("sock_addr");
    connect(SERVEUR,$adresse_complete) || die("connect");

    autoflush SERVEUR 1;
    printf SERVEUR "GET /$ARGV[1] HTTP/1.1\n";
    printf SERVEUR "Host:$ARGV[0]\n";
    printf SERVEUR "\n";

    while (<SERVEUR>)
    {
	print $_;
    }

    close (SERVEUR);
}

sub parse_request
{
    @request = split("/",$_[0]);
    $client = $request[0],"\n";
    $fichier = $request[$#request],"\n";
    $chemin = "$request[1]";
    for ($i = 2 ; $i < $#request ; $i++)
    {
	$chemin = "$chemin/$request[$i]";
    }
    return ("client" => $client, "path" => $chemin, "file" => $fichier);
}

$requete = "meleze12/Bureau/Systeme/TPlong/fichier.html";

%params = parse_request($requete);

print $params{"file"},"\n";
