#!/usr/bin/perl

sub parse_conf
{
    @tmp = ();
    %set = ();
    open(CONF,"comanche.conf");
    while(<CONF>)
    {
	chomp;
	@tmp = split('\s',$_) if(/set/);
	if ($tmp[0] ne "")
	{
	    $set{"$tmp[1]"} = "$tmp[2]";
	}
    }
    return %set;
}

%set = parse_conf();
foreach $k (keys(%set))
{
    print "$k => $set{$k}\n";
}
